version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nodejs-docker-training
    expose:
      - 3333
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    command: npm run dev
